### ISSUE TITLE
iOS: Avoid 300 ms onclick event delay by e.g. using fastclick.js library.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-examples#105]
In iOS there is a 300 ms delay between clicking e.g. a button and that its onclick event gets fired. Avoid this by for example using the [fastclick.js library](https://github.com/ftlabs/fastclick). Try first to solve the problem in a simpler way that doesn't require inclusion of any libraries.

**Comment by divineprog** [comment]
FastClick has been added to the Evothings JS library used by the examples. Closing issue.
