### ISSUE TITLE
SensorTag Library: Barometer calibration

### ISSUE THREAD

**Issue by divineprog** [evothings/evothings-examples#135]
Barometer calibration:

* setting value to 2 to obtain calibration value
* on success, set value to 1 to do the normal stuff

**Comment by Sionarch** [comment]
Implemented calibration procedure. Next step is to implement the pressure calculations based on the calibration data. A translation from Obj-C to JS has to be performed and attention kept to how typecasting to long long affects arithmetic operations.

**Comment by Sionarch** [comment]
long long integers on iOS are of length 8 bytes (256 bit). JavaScript integers undergoing bitwise operations are 32 bits long. In the pressure calculations, bit-shifts of more than 32 bits are performed in the Obj-C code, hence the JS calculations has to be rewritten.

**Comment by ardiri** [comment]
small correction - long long is by C-standard 64bit

http://en.wikipedia.org/wiki/Integer_%28computer_science%29#Long_long

i am sure it is possible to re-work the algorithm to fit within a 32bit
integer. i do not remember the objective-C code off hand; but i am pretty
sure they do not require long long to perform.

http://www.byteworks.us/Byte_Works/Blog/Entries/2012/10/31_Accessing_the_Bluetooth_low_energy_Barometer_on_the_TI_SensorTag.html

has the algorithm in their basic language:

      ! Update the pressure indicator.

      Tr = value(1) BITOR (value(2) << 8)

      S = m_barCalib(3) + Tr*(m_barCalib(4)/2^17 + Tr*m_barCalib(5)/2^34)

      O = m_barCalib(6)*2^14 + Tr*(m_barCalib(7)/8.0 +
Tr*m_barCalib(8)/2^19)

      Pr = (value(3) BITOR (value(4) << 8)) BITAND $00FFFF

      Pa = (S*Pr + O)/2^14


      ! Convert from Pascal to Bar.

      Pa = Pa/100000.0

      PRINT "Pressure: "; Pa; " Bar";



      ! Add the temperature.

      T = m_barCalib(2)/2^10 + Tr*m_barCalib(1)/2^24

      PRINT ", temperature: "; T

the only thing here that would potentially overflow would be the 2^34. you
could in fact get around this by using floats and converting the << and >>
to multiply and divide...  it would probably still give similar values; i
doubt the IEEE implementation would produce that many overflows.

should still be able to do this in pure javascript - and we should try!

On Sun, Apr 5, 2015 at 7:20 PM, Eric Svensson <notifications@github.com>
wrote:

> long long integers on iOS are of length 8 bytes (256 bit). JavaScript
> integers undergoing bitwise operations are 32 bits long. In the pressure
> calculations, bit-shifts of more than 32 bits are performed in the Obj-C
> code, hence the JS calculations has to be rewritten.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evothings/evothings-examples/issues/135#issuecomment-89739033>
> .
>



-- 
// Aaron Ardiri

**Comment by Sionarch** [comment]
Thanks.

Maybe you're right about long long being 64 bits. I might have misinterpreted this article: https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/Major64-BitChanges/Major64-BitChanges.html .

**Comment by Sionarch** [comment]
Haha, no it was rather that I was tricked by someone else, of course an 8 bytes integer is 64 bits ^__^

**Comment by fredrikeldh** [comment]
That article states the the *alignment* of long long increases from 4 to 
8 bytes.

The *size* of long long was always 8 bytes.

// Fredrik

Eric Svensson wrote:

**Comment by Sionarch** [comment]
Yes as I said I was tricked into believing that 8*8 was 256, haha ;)

**Comment by Sionarch** [comment]
Here's how I implemented the pressure calculations in JS. Please help me with rewriting it to avoid the overflow.

```
instance.getModelOneBarometerValues = function(data)
{
	var t = evothings.util.littleEndianToInt16(data, 0)
	var p = evothings.util.littleEndianToUint16(data, 2)
	var c = instance.barometerCalibrationData

	var S = c[2] + ((c[3] * t)/(1 << 17)) + ((c[4] * (t * t))/(1 << 34))
	var O = (c[5] * (1 << 14)) + (((c[6] * t)/(1 << 3))) + ((c[7] * (t * t))/(1 << 19))
	var Pa = (((S * p) + O) / (1 << 14))
	var pInterpreted = Pa / 100.0

	return { pressure: pInterpreted }
}
```

**Comment by ardiri** [comment]
Will have a look when I wake up tomorrow.Enjoy easter now :)// Aaron                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Eric SvenssonSent: Sunday, April 5, 2015 20:09To: evothings/evothings-examplesReply To: evothings/evothings-examplesCc: ardiriSubject: Re: [evothings-examples] SensorTag Library: Barometer calibration (#135)Here's how I implemented the pressure calculations in JS. Please help me with rewriting it to avoid the overflow.

instance.getModelOneBarometerValues = function(data)
{
    var t = evothings.util.littleEndianToInt16(data, 0)
    var p = evothings.util.littleEndianToUint16(data, 2)
    var c = instance.barometerCalibrationData

    var S = c[2] + ((c[3] * t)/(1 << 17)) + ((c[4] * (t * t))/(1 << 34))
    var O = (c[5] * (1 << 14)) + (((c[6] * t)/(1 << 3))) + ((c[7] * (t * t))/(1 << 19))
    var Pa = (((S * p) + O) / (1 << 14))
    var pInterpreted = Pa / 100.0

    return { pressure: pInterpreted }
}


—Reply to this email directly or view it on GitHub.

**Comment by ardiri** [comment]
just a quick question; what are the ranges of the calibration data? c[0] et
al.. are they 32 bit integers?

On Sun, Apr 5, 2015 at 8:09 PM, Eric Svensson <notifications@github.com>
wrote:

> Here's how I implemented the pressure calculations in JS. Please help me
> with rewriting it to avoid the overflow.
>
> instance.getModelOneBarometerValues = function(data)
> {
>     var t = evothings.util.littleEndianToInt16(data, 0)
>     var p = evothings.util.littleEndianToUint16(data, 2)
>     var c = instance.barometerCalibrationData
>
>     var S = c[2] + ((c[3] * t)/(1 << 17)) + ((c[4] * (t * t))/(1 << 34))
>     var O = (c[5] * (1 << 14)) + (((c[6] * t)/(1 << 3))) + ((c[7] * (t * t))/(1 << 19))
>     var Pa = (((S * p) + O) / (1 << 14))
>     var pInterpreted = Pa / 100.0
>
>     return { pressure: pInterpreted }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evothings/evothings-examples/issues/135#issuecomment-89748648>
> .
>



-- 
// Aaron Ardiri

**Comment by Sionarch** [comment]
///Calibration values unsigned
@property UInt16 c1,c2,c3,c4;
///Calibration values signed
@property int16_t c5,c6,c7,c8;

**Comment by ardiri** [comment]
ok. here is a small pattern i have released - which may come in useful for
solving this.

int main()
{
  fprintf(stdout, "%d\n", 1000 / (1 << 3));
  fprintf(stdout, "%d\n", 1000 >> 3);
}
both of these result in the same number.. 1000 / 8 - with a result of 125.
looking at the functions below, we should be able to update them accordingly

instance.getModelOneBarometerValues = function(data)
{
    var t = evothings.util.littleEndianToInt16(data, 0)
    var p = evothings.util.littleEndianToUint16(data, 2)
    var c = instance.barometerCalibrationData

    var S = c[2] + ((c[3] * t)/(1 << 17)) + ((c[4] * (t * t))/(1 << 34))
    var O = (c[5] * (1 << 14)) + (((c[6] * t)/(1 << 3))) + ((c[7] * (t
* t))/(1 << 19))
    var Pa = (((S * p) + O) / (1 << 14))
    var pInterpreted = Pa / 100.0

    return { pressure: pInterpreted }
}

which would result in the above being re-written as:

instance.getModelOneBarometerValues = function(data)
{
    var t = evothings.util.littleEndianToInt16(data, 0)
    var p = evothings.util.littleEndianToUint16(data, 2)
    var c = instance.barometerCalibrationData

    var S = c[2] + ((c[3] * t) >> 17) + ((c[4] * (t * t)) >> 34)
    var O = (c[5] << 14) + (((c[6] * t) >> 3)) + ((c[7] * (t * t)) >> 19)
    var Pa = (((S * p) + O) >> 14)
    var pInterpreted = Pa / 100.0

    return { pressure: pInterpreted }
}

assuming that the values would not overflow; i think the use of >> and
<< will force the javascript compiler to keep the values as integers
and not treat them as floats. so, we may need to update the algorithms
to remove them - we could try the above; and see if we are lucky.

instance.getModelOneBarometerValues = function(data)
{
    var t = evothings.util.littleEndianToInt16(data, 0)
    var p = evothings.util.littleEndianToUint16(data, 2)
    var c = instance.barometerCalibrationData

    var S = c[2] + ((c[3] * t) / 131072) + ((c[4] * (t * t)) / 17179869184.0)
    var O = (c[5] * 16384.0) + (((c[6] * t) / 8)) + ((c[7] * (t * t))
/ 524288.0)
    var Pa = (((S * p) + O) / 16384.0)
    var pInterpreted = Pa / 100.0

    return { pressure: pInterpreted }
}

these should; theoretically be the same calculations but using
floating point mathemetics instead.
(>> x) is basically the same as (divide by 2^x) and (<< x) is
basically the same as (multiply by 2^x)



On Sun, Apr 5, 2015 at 9:31 PM, Aaron Ardiri <aaron@ardiri.com> wrote:

> just a quick question; what are the ranges of the calibration data? c[0]
> et al.. are they 32 bit integers?
>
> On Sun, Apr 5, 2015 at 8:09 PM, Eric Svensson <notifications@github.com>
> wrote:
>
>> Here's how I implemented the pressure calculations in JS. Please help me
>> with rewriting it to avoid the overflow.
>>
>> instance.getModelOneBarometerValues = function(data)
>> {
>>     var t = evothings.util.littleEndianToInt16(data, 0)
>>     var p = evothings.util.littleEndianToUint16(data, 2)
>>     var c = instance.barometerCalibrationData
>>
>>     var S = c[2] + ((c[3] * t)/(1 << 17)) + ((c[4] * (t * t))/(1 << 34))
>>     var O = (c[5] * (1 << 14)) + (((c[6] * t)/(1 << 3))) + ((c[7] * (t * t))/(1 << 19))
>>     var Pa = (((S * p) + O) / (1 << 14))
>>     var pInterpreted = Pa / 100.0
>>
>>     return { pressure: pInterpreted }
>> }
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/evothings/evothings-examples/issues/135#issuecomment-89748648>
>> .
>>
>
>
>
> --
> // Aaron Ardiri
>



-- 
// Aaron Ardiri

**Comment by Sionarch** [comment]
Nice, your second proposed solution seems to work well! I agree with your reasoning about why this works.

**Comment by Sionarch** [comment]
https://github.com/evothings/evothings-examples/pull/137

**Comment by ardiri** [comment]
+1 awesome :)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Eric SvenssonSent: Monday, April 6, 2015 01:57To: evothings/evothings-examplesReply To: evothings/evothings-examplesCc: ardiriSubject: Re: [evothings-examples] SensorTag Library: Barometer calibration (#135)Nice, your second proposed solution seems to work well! I agree with your reasoning about why this works.

—Reply to this email directly or view it on GitHub.

**Comment by divineprog** [comment]
Barometer has been tested OK on both CC2541 and CC2650 with the refactored TI SensorTag library. Closing issue.
