### ISSUE TITLE
redbear-simplechat running in an html5 configuration?

### ISSUE THREAD

**Issue by cordphelps** [evothings/evothings-examples#142]
I'm trying to get redbear-simplechat running in an html5 configuration absent Evothings Studio.

I thought I could grab the *.js and just load them with script tags in the head of the html, then run app.initialize();

after doing that, app.startScan() fails with 'evothings.ble is undefined' app.js (line 76)

please ref: https://github.com/cordphelps/evothings-redbear

Am I thinking about this the right way? Sorry, I'm hazy on plugings. Thanks.

**Comment by cordphelps** [comment]
I think I'm close; what's the relationship between evothings.easyble.{} and evothings.ble.{}  ?

**Comment by fredrikeldh** [comment]
```evothings.easyble``` is defined by ```easyble.js```. It is a helper layer which works on top of ```evothings.ble```, which is the object exported by the plugin [cordova-ble](https://github.com/evothings/cordova-ble).

You need a cordova app with that plugin. The simplest way of getting such an app is downloading "Evothings Client" from the app store.

**Comment by cordphelps** [comment]
thank you. I would be cool is evothings would support the phonegapBuild plugin model

(http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins)
