### ISSUE TITLE
easyble.js should support multiple characteristics with the same UUID in different services.

### ISSUE THREAD

**Issue by fredrikeldh** [evothings/evothings-examples#150]
Forum thread: http://evothings.com/forum/viewtopic.php?f=8&t=1441

**Comment by fredrikeldh** [comment]
We should add functions readServiceCharacteristic() and writeServiceCharacteristic().

**Comment by jrobeson** [comment]
isn't this solved now? easyble seems to contain both readServiceCharacteristic and writeServiceCharacteristic

**Comment by mikaelkindborg** [comment]
Yes this issue should be solved, added missing documentation comments. Closing this issue.

easyble.js is now in evothings-libraries, see this commit for the documentation comment update: https://github.com/evothings/evothings-libraries/commit/50b91d32fd77131612faed174580bd81daaa0d34
