### ISSUE TITLE
Improve the README for the Arduino LED On/Off TCP example

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-examples#152]
Add instructions to the README for the Arduino LED On/Off TCP example about what needs to be modified in the Arduino WiFi code to enable it to connect to the network through WiFi. These instructions should say that the user needs to scroll down in the Arduino code to e.g. the 'ssid' and 'pass' variables and modify these in accordance with the user's local WiFi network.

**Comment by fredrikeldh** [comment]
We could add an #error directive near the WiFi credential lines. This will prevent compilation until the user has edited the code.

**Comment by ChristJO** [comment]
hi please how do we add more buttons to the arduino code??
