### ISSUE TITLE
scanRecord set to empty string on iOS fails TI sensortag scan

### ISSUE THREAD

**Issue by jahbini** [evothings/evothings-examples#153]
The commentary on `evothings/ble.js` indicates that `scanRecord` is not available on iOS.  The corresponding  code in EVOBLE.m for iOS specifically sets `scanRecord` to the empty string, subsequently the `easyble.js` routine `ensureAdvertisementData` fails when this happens, rejecting any device connection.

Is there a suggested workaround? (otherwise, I'll just fake it, till I make it)

**`evothings/easyble/easyble.js`**
```
	internal.ensureAdvertisementData = function(device)
	{
		// If device object already has advertisementData we
		// do not need to parse the scanRecord.
		if (device.advertisementData) { return; }

		// Must have scanRecord yo continue.
		if (!device.scanRecord) { return; } 
```
***Device scan fails to log device at this point***

**`EVOBLE.m`**
```
/**
 * Internal helper method.
 */
- (void) sendScanInfoForPeriperhal: (CBPeripheral *)peripheral
	RSSI: (NSNumber *)RSSI
{
	// Create an info object.
	// The UUID is used as the address of the device (the 6-byte BLE address
	// does not seem to be directly available on iOS).
	NSDictionary* info = @{
		@"address" : [peripheral.identifier UUIDString],
		@"rssi" : RSSI,
		@"name" : (peripheral.name != nil) ? peripheral.name : [NSNull null],
		@"scanRecord" : @""
	};

	// Send back data to JS.
	if (self.scanCallbackId)
	{
		[self
			sendDictionary: info
			forCallback: self.scanCallbackId
			keepCallback: YES];
	}
}

```

**Comment by fredrikeldh** [comment]
You must update your Evothings Client to at least 1.1.3. That contains an newer version of the BLE plugin which supplies advertiesementData on iOS.
