### ISSUE TITLE
Fastclick.js conflicts with Ionic framework's click handling.

### ISSUE THREAD

**Issue by Sionarch** [evothings/evothings-examples#160]
The Fastclick.js library that is loaded by evothings.js conflicts with the click/tap handling of the Ionic framework. For this reason, click events don't fire properly when both the ionic framework and evothings.js are loaded. This might also be true for click/tap event handling in the Angular JS framework, because Ionic utilizes this in its click/tap handling.

Solve this for example by either detecting whether other click/tap handling is present and then skip loading fastclick.js, or make it apparent that fastclick.js shouldn't be included at the same time as the Ionic framework, by e.g. allowing easy exclusion of it through editing index.html and let the user remove it themself.

**Comment by mikaelkindborg** [comment]
This has been solved by including libs/evothings/ui/ui.js explicitly in all example index.html files, like this:

    <script src="libs/evothings/ui/ui.js"></script>

ui.js in turn includes fastclick and applies fastclick to the DOM.

People who do not want fastclick can remove the include of ui.js or edit ui.js to meet their needs.
