### ISSUE TITLE
onDisconnection()

### ISSUE THREAD

**Issue by jmparatte** [evothings/evothings-examples#168]
Hi,

A new issue has gone with latest revision:
Error: No instance of overloaded function "BLE::onDisconnection" matches the argument list in "main.cpp", Line: 193, Col: 10

138:
void onDisconnection(Gap::Handle_t handle, 
                     Gap::DisconnectionReason_t disconnectReason) 
{
  INFO_NL(">> disconnected");
  ble.startAdvertising();
  INFO_NL(">> device advertising");
}

193:
    ble.onDisconnection(onDisconnection);

**Comment by fredrikeldh** [comment]
This relates to the example "nordic-nRF51-dk-ble".

**Comment by ardiri** [comment]
you might want to check a previous forum post - chances are the API has changed.

http://forum.evothings.com/viewtopic.php?f=8&t=1468

**Comment by jmparatte** [comment]
Hi fredrikeldh , Yes it's about "nordic-nRF51-dk-ble", I missed this information.

Hi ardiri, I've commented line 193 "ble.onDisconnection(onDisconnection);" for compilation goes right. I've tried this example with EvoThings Studio: I can set/clear the 4 leds but can't read buttons.

**Comment by ardiri** [comment]
thats not the solution; the BLE_API header files changes on 29th Sep 2015.
here is a patch:

@@ -135,8 +135,7 @@ void onDataWritten(const GattWriteCallbackParams *context)
   } 
 }
 
-void onDisconnection(Gap::Handle_t handle, 
-                     Gap::DisconnectionReason_t disconnectReason) 
+void onDisconnection(const Gap::DisconnectionCallbackParams_t *params)  
 {
   INFO_NL(">> disconnected");
   ble.startAdvertising();

we can close this issue - the patch is listed above.

**Comment by jmparatte** [comment]
OK, thans, all rights now.

 

De : ardiri [mailto:notifications@github.com] 
Envoyé : mercredi 30 septembre 2015 11:32
À : evothings/evothings-examples
Cc : Jean-Marc Paratte
Objet : Re: [evothings-examples] onDisconnection() (#168)

 

thats not the solution; the BLE_API header files changes on 29th Sep 2015.
here is a patch:

@@ -135,8 +135,7 @@ void onDataWritten(const GattWriteCallbackParams *context)
} 
}

-void onDisconnection(Gap::Handle_t handle, 

*	Gap::DisconnectionReason_t disconnectReason) +void onDisconnection(const Gap::DisconnectionCallbackParams_t *params)
{ INFO_NL(">> disconnected"); ble.startAdvertising();

we can close this issue - the patch is listed above.

**Comment by ardiri** [comment]
the example and the blog post should be updated to reflect these changes. there was a big commit from the bluetooth team yesterday which is impacted the example code - unfortunately we can only find out too late when they break the API implementation. // Aaron                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jean-Marc ParatteSent: Wednesday, September 30, 2015 14:17To: evothings/evothings-examplesReply To: evothings/evothings-examplesCc: ardiriSubject: Re: [evothings-examples] onDisconnection() (#168)OK, thans, all rights now.

 

De : ardiri [mailto:notifications@github.com] 
Envoyé : mercredi 30 septembre 2015 11:32
À : evothings/evothings-examples
Cc : Jean-Marc Paratte
Objet : Re: [evothings-examples] onDisconnection() (#168)

 

thats not the solution; the BLE_API header files changes on 29th Sep 2015.
here is a patch:

@@ -135,8 +135,7 @@ void onDataWritten(const GattWriteCallbackParams *context)
} 
}

-void onDisconnection(Gap::Handle_t handle, 

*	Gap::DisconnectionReason_t disconnectReason) +void onDisconnection(const Gap::DisconnectionCallbackParams_t *params)
{ INFO_NL(">> disconnected"); ble.startAdvertising();

we can close this issue - the patch is listed above.

—
Reply to this email directly or view it on GitHub <https://github.com/evothings/evothings-examples/issues/168#issuecomment-144338161> .Image supprimée par l'expéditeur.



—Reply to this email directly or view it on GitHub.
