### ISSUE TITLE
Add example apps to Beta 2

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-examples#176]
Add the example apps we didn't have time for in Beta 1
* Amazon AWS, example
* New MediaTek MediaTek Linkit Connect 7681
* ESP 8266
* Ionic?
* Facebook, Parse IoT cloud x 2

**Comment by gokr** [comment]
We do only New MediaTek MediaTek Linkit Connect 7681 and ESP 8266 for beta 2.

**Comment by mikaelkindborg** [comment]
Done.

Documentation added in this commit: https://github.com/mikaelkindborg/evothings-doc/commit/2ad16984b31fca8cd933b0657239343b878d7807

Examples added to Workbench in this commit: https://github.com/mikaelkindborg/evothings-studio/commit/9e3879dfd96b827756e8db8c34ea64f56520446f
