### ISSUE TITLE
Dialog Blinky app does not work on Android (Evothings Viewer 1.4)

### ISSUE THREAD

**Issue by nbezembinder1** [evothings/evothings-examples#196]
The Dialog - Blinky app no longer works when using the new Evothings Viewer (version 1.4). This is related to the following issue: https://github.com/evothings/evothings-libraries/pull/8#issuecomment-220940384

Once the issue is fixed in the `easyble` library the example can be edited to use the new functions like so https://github.com/nbezembinder1/nbezembinder1.github.io/commit/8647775643713aa162b9542e8d9be74b5b8cab5a

**Comment by nbezembinder1** [comment]
Fixed: https://github.com/evothings/evothings-examples/commit/3fd6bd6c53cefdf5bb4a7b7a83f4f208abefb6a9

**Comment by mikaelkindborg** [comment]
@nbezembinder1 Hi, finally merged your pull request! Many thanks! I reverted some commits, the order of params in easyble.startScan and writeCharacteristicWithoutResponse. I added writeServiceCharacteristicWithoutResponse in the main branch, and I plan to update easyble.startScan as you suggest. The reason that startScan did not work for you was a bug that was fixed on the master branch.
