### ISSUE TITLE
"Dialog IoT Sensor Starter Guide" doesn't function

### ISSUE THREAD

**Issue by InventorSector** [evothings/evothings-examples#202]
@mikaelkindborg
I'm trying to run https://evothings.com/dialog-iot-sensor-starter-guide/
I've done everything according to instructions but when i run i get 

> Cannot read property 'createInstance' of undefined .. 

and when i press 'Connect'

> Cannot read property 'connectToClosestSensor' of undefined ...

My dialog modules are running smoothly in the "dialog semiconductor.." example, so i guess their SFL firmware is the latest (i haven't changed anything and the modules are fresh bought).

What could i been doing wrong? Below is my initial app.js

```
document.addEventListener('deviceready',	
	function() { evothings.scriptsLoaded(initialize) }, false
);

var iotsensor;


function initialize() 
{ 
	console.log("Initialize function called"); 
	iotsensor = evothings.iotsensor.createInstance(evothings.iotsensor.SFL);
        iotsensor.accelerometerCallback(handleAccelerometerData);
}



function connect()
{
	iotsensor.connectToClosestSensor(
		7500, // Scan for 7500 ms
		function()
		{
			console.log("Connected to IoT Sensor");
		},
		function(error)
		{
			console.log('Disconnect error ' + error);
		}
	);
}



function accelerometerOn()
{
	iotsensor.accelerometerOn();
}

function handleAccelerometerData(data)
{
	console.log('x: ' + data.x + ' y: ' + data.y + ' z: ' + data.z);
	//var now = Date.now();

	//line_x.append(now, data.x);
	//line_y.append(now, data.y);
	//line_z.append(now, data.z);

	//window.accel_xyz = data;
}
```

Thanx

**Comment by nbezembinder1** [comment]
Could you add the source code for the index.html file? Looks like the JavaScript libraries are not loaded correctly

**Comment by InventorSector** [comment]
@nbezembinder1  @mikaelkindborg
Here's the index file code, exactly as instructed in started guide https://evothings.com/dialog-iot-sensor-starter-guide/


```
<!DOCTYPE html>
<html>

<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, user-scalable=no,
		shrink-to-fit=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />

	<title>Dialog IoT Sensor Jyro</title>

	<style>
		@import 'ui/css/evothings-app.css';
	</style>

	<script>
	// Redirect console.log to Evothings Workbench.
	if (window.hyper && window.hyper.log) { console.log = hyper.log }
	</script>

</head>

<body ontouchstart=""><!-- ontouchstart="" enables low-delay CSS transitions. -->

	<header>
		<button class="back" onclick="history.back()">
			<img src="ui/images/arrow-left.svg" />
		</button>

		<img class="logotype" src="ui/images/logo.svg" alt="Evothings" />

		<!--<button class="menu" onclick=""><img src="ui/images/menu.svg" /></button>-->
	</header>

	<h1>Jyro app v.1</h1>

	<p>This is a basic template for an Evothings app.</p>
	
	<button class="blue wide" onclick="connect()">Connect</button>
	<button class="blue wide" onclick="accelerometerOn()">Accelerometer On</button>
	

	<script src="cordova.js"></script>
	<script src="libs/evothings/evothings.js"></script>
	<script src="libs/evothings/ui/ui.js"></script>
	<script src="libs/evothings/dialog-iotsensor/iotsensor.js"></script>
	<script src="app.js"></script>
	


	<!-- TODO: Add libraries that you need -->

</body>

</html>

```

**Comment by nbezembinder1** [comment]
I just tried your code myself and it works as expected:

http://puu.sh/q61Vm/0a93596f28.png

That probably means the files required by the app are not properly added to the correct folders. You need to make sure you folder layout looks as follows:

```
└───Jyro
    │   app-icon.png
    │   app.js
    │   evothings.json
    │   index.html
    │   
    ├───libs
    │   ├───evothings
    │   │   │   evothings.js
    │   │   │   VERSION
    │   │   │   
    │   │   ├───dialog-iotsensor
    │   │   │       iotsensor-ble.js
    │   │   │       iotsensor-raw.js
    │   │   │       iotsensor-settings.js
    │   │   │       iotsensor-sfl.js
    │   │   │       iotsensor.js
    │   │   │       
    │   │   ├───easyble
    │   │   │       easyble.js
    │   │   │       
    │   │   ├───ui
    │   │   │       fastclick.js
    │   │   │       ui.js
    │   │   │       
    │   │   └───util
    │   │           util.js
    │   │           
    │   └───jquery
    └───ui
        ├───css
        ├───fonts
        └───images
```

**Comment by InventorSector** [comment]
@nbezembinder1
thanx a lot for fast and thorough reply!
Damn i've got it all the same, except i also have 'smothie' folder in libs and inside it smoothie.js , package.json, bower.json , smoothie.d.ts.

I've also followed  https://evothings.com/doc/build/cordova-install-osx.html and done everything successfully except "Install Android Developer Tools (ADT)"...

I can't get it.. Could more info help you out?

**Comment by nbezembinder1** [comment]
@InventorSector 

This app is meant to run within the Evothings Viewer application on your smartphone (Android or iOS). Building your own application using Cordova takes a lot more time since you also need to add the proper Cordova plugins. Please download the Evothings Viewer app on your smartphone from the App/Play Store and connect the app to the Evothings Workbench.

See https://evothings.com/doc/tutorials/evothings-studio-getting-started.html for more info.

Also, I believe your IoT Sensor modules are running the correct firmware. If you have more questions regarding the firmware you can go to the [Dialog support website](http://support.dialog-semiconductor.com/).

**Comment by InventorSector** [comment]
Evo viewer etc are all downloaded and fully functionable. 
For example, when i run the original example from evothings (Dialog semiconductor IoT sensor), it works perfectly!(that's also why i think it's not an SFL problem)

cordova etc i downloaded only to have everything needed just in case that was what caused my trouble (but apparently it wasn't..)

**Comment by nbezembinder1** [comment]
Could you zip the contents of your project folder and send it to me at `nick.bezembinder @ gmail.com` and I will try to figure out what the problem is.

**Comment by InventorSector** [comment]
@nbezembinder1  
wow man, really thanx for such a big help!

**Comment by InventorSector** [comment]
nbezembinder1 helped me out, and what was happening was that i saved the files by right clicking on each file and 'save link as', so  they were saved under the .js extension but they were html files..

Copying the whole code and pasting it in the .js file solved the problem. It works smoothly now, so once again big thanx @nbezembinder1 !
